/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UpdateInvoiceFromBrandReply': EventHandler<{ messageId: string; source: string; body: string; senderId?: string; sender?: unknown }, never>
    'UpdateInvoiceDraft': ApiRouteHandler<{ invoiceNumber?: string; invoiceDate?: string; dueDate?: string; campaignName?: string; brandSnapshot?: { name?: string; email?: string; pocName?: string; gstin?: string; address?: string }; gstAmount?: number; tdsAmount?: number; netPayable?: number }, ApiResponse<200, { success: boolean; invoice: unknown }> | ApiResponse<400, { success: boolean; error: string; issues?: Array<unknown> }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'RequestMissingInvoiceDetails': EventHandler<{ invoiceId: string; dealId: string; creatorId?: string; status?: string; missingFields?: Array<unknown> }, never>
    'GetInvoices': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; invoices: Array<{ invoiceId: string; dealId: string; creatorId: string; status: 'draft' | 'awaiting_details' | 'sent'; invoiceNumber?: string; invoiceDate: string; dueDate: string; creatorSnapshot: unknown; brandSnapshot: { name?: string; email?: string; pocName?: string; gstin?: string; address?: string }; deliverables: Array<string>; campaignName?: string; amount: number; gstAmount?: number; tdsAmount?: number; netPayable?: number; missingFields?: Array<string>; createdAt: string; updatedAt: string }>; count: number }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'GetInvoice': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; invoice: { invoiceId: string; dealId: string; creatorId: string; status: 'draft' | 'awaiting_details' | 'sent'; invoiceNumber?: string; invoiceDate: string; dueDate: string; creatorSnapshot: unknown; brandSnapshot: { name?: string; email?: string; pocName?: string; gstin?: string; address?: string }; deliverables: Array<string>; campaignName?: string; amount: number; gstAmount?: number; tdsAmount?: number; netPayable?: number; missingFields?: Array<string>; createdAt: string; updatedAt: string } }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'CreateOrGetInvoiceDraft': EventHandler<{ dealId: string; creatorId?: string }, { topic: 'invoice.draft_created'; data: { invoiceId: string; dealId: string; creatorId?: string; status?: string; missingFields?: Array<unknown> } }>
    'SendInvoiceEmail': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string; emailId?: string; invoice: unknown }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'GetInvoiceByDeal': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; invoice: { invoiceId: string; dealId: string; creatorId: string; status: 'draft' | 'awaiting_details' | 'sent'; invoiceNumber?: string; invoiceDate: string; dueDate: string; creatorSnapshot: unknown; brandSnapshot: { name?: string; email?: string; pocName?: string; gstin?: string; address?: string }; deliverables: Array<string>; campaignName?: string; amount: number; gstAmount?: number; tdsAmount?: number; netPayable?: number; missingFields?: Array<string>; createdAt: string; updatedAt: string } }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'CreateOrGetInvoice': ApiRouteHandler<{ dealId: string; creatorId?: string }, ApiResponse<200, { success: boolean; status: 'created' | 'exists'; invoice: { invoiceId: string; dealId: string; creatorId: string; status: 'draft' | 'awaiting_details' | 'sent'; invoiceNumber?: string; invoiceDate: string; dueDate: string; creatorSnapshot: unknown; brandSnapshot: { name?: string; email?: string; pocName?: string; gstin?: string; address?: string }; deliverables: Array<string>; campaignName?: string; amount: number; gstAmount?: number; tdsAmount?: number; netPayable?: number; missingFields?: Array<string>; createdAt: string; updatedAt: string } }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<404, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, { topic: 'invoice.draft_created'; data: { invoiceId: string; dealId: string; creatorId?: string; status?: string; missingFields?: Array<unknown> } }>
    'UpdateDealNegotiation': EventHandler<never, { topic: 'deal.updated'; data: never }>
    'RateCalculationWorkflow': EventHandler<never, { topic: 'RateRecommendationGenerated'; data: never }>
    'NotifyDealCreated': EventHandler<never, never>
    'NegotiationContextGate': EventHandler<never, { topic: 'NegotiationEvaluationRequested'; data: never }>
    'HandleDealUpdate': EventHandler<never, never>
    'CreatorDecisionBridge': EventHandler<never, { topic: 'deal.accepted'; data: { dealId: string; creatorId?: string } }>
    'CreateDealFromInquiry': EventHandler<{ inquiryId: string; source: string; extracted: unknown; sender?: unknown }, { topic: 'deal.created'; data: never } | { topic: 'deal.updated'; data: never } | { topic: 'NegotiationEvaluationRequested'; data: never }>
    'BrandInquiryBridge': EventHandler<never, never>
    'BrandContextUpdated': EventHandler<never, { topic: 'BrandContextUpdated'; data: never }>
    'EnrichSender': EventHandler<never, { topic: 'message.enriched'; data: never }>
    'EnsureCreatorProfile': EventHandler<{ creatorId: string; requiredFields?: Array<string> }, never>
    'GetCreatorProfile': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { exists: boolean; profile?: unknown }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'CreateOrUpdateCreatorProfile': ApiRouteHandler<{ creatorId: string; fullName?: string; businessName?: string; email?: string; phone?: string; address?: string; pan?: string; gstin?: string; bankName?: string; accountNumber?: string; ifsc?: string; upiId?: string; socials?: Array<{ platform: 'instagram' | 'youtube' | 'twitter' | 'linkedin' | 'facebook' | 'whatsapp'; handle: string; url?: string; followers?: unknown }>; defaultPaymentTermsDays?: unknown; lateFeePercent?: number }, ApiResponse<200, { success: boolean; profile: unknown }> | ApiResponse<400, { success: boolean; error: string; issues?: Array<unknown> }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'NotifyCreator': EventHandler<{ creatorId: string }, never>
    'FetchCompetitorContent': EventHandler<{ creatorId: string; competitors?: Array<{ platform?: string; external_id?: string; name?: string; follower_count?: number }> }, { topic: 'competitor.metrics.calculate'; data: { creatorId: string } }>
    'DiscoverCompetitors': EventHandler<{ creatorId: string }, { topic: 'competitor.content.fetch'; data: { creatorId: string; competitors?: Array<{ platform?: string; external_id?: string; name?: string; follower_count?: number }> } }>
    'CalculateMetrics': EventHandler<{ creatorId: string }, { topic: 'competitor.ai.analyze'; data: { creatorId: string } }>
    'CompetitorAnalyze': ApiRouteHandler<{ creatorId: string }, ApiResponse<200, { success: boolean; message: string; workflowId?: string }> | ApiResponse<400, { success: boolean; error: string }> | ApiResponse<409, { success: boolean; error: string; status: 'running' | 'completed' | 'failed' }> | ApiResponse<500, { success: boolean; error: string; details?: string }>, { topic: 'competitor.discover'; data: { creatorId: string } }>
    'AIAnalysis': EventHandler<{ creatorId: string }, { topic: 'competitor.notify.creator'; data: { creatorId: string } }>
    'RateRecommendation': ApiRouteHandler<{ brandDetails: { brandName: string; deliverables: string; proposedBudget?: number | unknown }; creatorMetrics: { niche: string; followers: number; platform: 'instagram' | 'youtube' | 'facebook'; contentType: 'reel' | 'video' | 'post' | 'short'; country?: 'India' | 'US'; avgLikes: number; avgComments: number; avgShares: number; avgViews: number; postsLast30Days: number } }, unknown, never>
    'GetInquiries': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FacebookWebhookVerify': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FacebookWebhookEvent': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'message.received'; data: never }>
    'EmailWebhookEvent': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'message.received'; data: never }>
    'UpdateDeal': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'deal.updated'; data: never }>
    'SendAutoReply': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'deal.updated'; data: never }>
    'GetDashboardStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDeals': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDealById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreatorActions': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'StoreInquiry': EventHandler<{ messageId: string; source: string; body: string; subject?: string; senderId?: string; sender?: unknown; isBrandInquiry: boolean; confidence?: number; reasoning?: string; keywords?: Array<unknown>; classifiedAt?: string }, { topic: 'inquiry.received'; data: { inquiryId: string; source: string; body: string; senderId?: string; threadKey?: string; sender?: { name?: string; platform?: string; id?: string } } }>
    'ExtractInquiry': EventHandler<{ inquiryId: string; source: string; body: string; senderId?: string; threadKey?: string; sender?: { name?: string; platform?: string; id?: string } }, { topic: 'inquiry.extracted'; data: { inquiryId: string; source: string; extracted: unknown; sender?: unknown } }>
    'ClassifyMessage': EventHandler<{ messageId: string; source: string; body: string; senderId?: string; sender?: { name?: unknown; platform?: string; id?: string }; subject?: unknown; pageName?: unknown }, { topic: 'message.classified'; data: { messageId: string; source: string; body: string; subject?: string; senderId?: string; sender?: unknown; isBrandInquiry: boolean; confidence?: number; reasoning?: string; keywords?: Array<unknown>; classifiedAt?: string } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
  }
    
}