/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'NotifyDealCreated': EventHandler<never, never>
    'HandleDealUpdate': EventHandler<never, never>
    'CreateDealFromInquiry': EventHandler<{ inquiryId: string; source: string; extracted: unknown; sender?: unknown }, { topic: 'deal.created'; data: never }>
    'EnrichSender': EventHandler<never, { topic: 'message.enriched'; data: { messageId: string; source: string; body: string; senderId?: string; sender?: { name?: string; platform?: string; id?: string }; subject?: string; pageName?: string } }>
    'GetInquiries': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FacebookWebhookVerify': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FacebookWebhookEvent': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'message.received'; data: never }>
    'EmailWebhookEvent': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'message.received'; data: never }>
    'UpdateDeal': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'deal.updated'; data: never }>
    'SendAutoReply': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDashboardStats': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDeals': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDealById': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreatorActions': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'StoreInquiry': EventHandler<{ messageId: string; source: string; body: string; subject?: string; senderId?: string; sender?: unknown; isBrandInquiry: boolean; confidence?: number; reasoning?: string; keywords?: Array<unknown>; classifiedAt?: string }, { topic: 'inquiry.received'; data: { inquiryId: string; source: string; body: string; senderId?: string; sender?: { name?: string; platform?: string; id?: string } } }>
    'ExtractInquiry': EventHandler<{ inquiryId: string; source: string; body: string; senderId?: string; sender?: { name?: string; platform?: string; id?: string } }, { topic: 'inquiry.extracted'; data: { inquiryId: string; source: string; extracted: unknown; sender?: unknown } }>
    'ClassifyMessage': EventHandler<{ messageId: string; source: string; body: string; senderId?: string; sender?: { name?: string; platform?: string; id?: string }; subject?: string; pageName?: string }, { topic: 'message.classified'; data: { messageId: string; source: string; body: string; subject?: string; senderId?: string; sender?: unknown; isBrandInquiry: boolean; confidence?: number; reasoning?: string; keywords?: Array<unknown>; classifiedAt?: string } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
  }
    
}